# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pulsewaves.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pulsewaves.proto',
  package='',
  serialized_pb=_b('\n\x10pulsewaves.proto\"\xa5\x01\n\x07PWListP\x12\x0f\n\x07xOffset\x18\x01 \x02(\x01\x12\x0f\n\x07yOffset\x18\x02 \x02(\x01\x12\x0f\n\x07zOffset\x18\x03 \x02(\x01\x12\x0e\n\x06xScale\x18\x04 \x02(\x01\x12\x0e\n\x06yScale\x18\x05 \x02(\x01\x12\x0e\n\x06zScale\x18\x06 \x02(\x01\x12\x0f\n\x07tOffset\x18\x07 \x02(\x01\x12\x0e\n\x06tScale\x18\x08 \x02(\x01\x12\x16\n\x05pulse\x18\t \x03(\x0b\x32\x07.PulseP\"\xe5\x02\n\x06PulseP\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x1b\n\x08\x63hannels\x18\x02 \x03(\x0b\x32\t.ChannelP\x12\x0f\n\x07\x61nchorX\x18\x03 \x02(\x05\x12\x0f\n\x07\x61nchorY\x18\x04 \x02(\x05\x12\x0f\n\x07\x61nchorZ\x18\x05 \x02(\x05\x12\x0f\n\x07targetX\x18\x06 \x02(\x05\x12\x0f\n\x07targetY\x18\x07 \x02(\x05\x12\x0f\n\x07targetZ\x18\x08 \x02(\x05\x12\x1c\n\x14\x66irstReturningSample\x18\t \x02(\r\x12\x1b\n\x13lastReturningSample\x18\n \x02(\r\x12\x1c\n\x14pulseDescriptorIndex\x18\x0b \x01(\r\x12\x16\n\x0e\x65\x64geOfScanLine\x18\x0c \x01(\x08\x12\x15\n\rscanDirection\x18\r \x01(\x08\x12\x12\n\nmirroFacet\x18\x0e \x01(\r\x12\x11\n\tintensity\x18\x0f \x01(\r\x12\x16\n\x0e\x63lassification\x18\x10 \x01(\r\"S\n\x08\x43hannelP\x12\x0f\n\x07\x63hannel\x18\x01 \x02(\r\x12\x12\n\nsampleUnit\x18\x02 \x02(\x02\x12\"\n\x0bwaveSegment\x18\x03 \x03(\x0b\x32\r.WaveSegmentP\"8\n\x0cWaveSegmentP\x12\x1a\n\x12\x64urationFromAnchor\x18\x01 \x02(\x02\x12\x0c\n\x04\x65\x63ho\x18\x02 \x03(\rB.\n\"umg.core.lidar.protobuf.pulsewavesB\x08PWProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PWLISTP = _descriptor.Descriptor(
  name='PWListP',
  full_name='PWListP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xOffset', full_name='PWListP.xOffset', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yOffset', full_name='PWListP.yOffset', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zOffset', full_name='PWListP.zOffset', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xScale', full_name='PWListP.xScale', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yScale', full_name='PWListP.yScale', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zScale', full_name='PWListP.zScale', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tOffset', full_name='PWListP.tOffset', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tScale', full_name='PWListP.tScale', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pulse', full_name='PWListP.pulse', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=186,
)


_PULSEP = _descriptor.Descriptor(
  name='PulseP',
  full_name='PulseP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='PulseP.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channels', full_name='PulseP.channels', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='anchorX', full_name='PulseP.anchorX', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='anchorY', full_name='PulseP.anchorY', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='anchorZ', full_name='PulseP.anchorZ', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetX', full_name='PulseP.targetX', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetY', full_name='PulseP.targetY', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='targetZ', full_name='PulseP.targetZ', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='firstReturningSample', full_name='PulseP.firstReturningSample', index=8,
      number=9, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastReturningSample', full_name='PulseP.lastReturningSample', index=9,
      number=10, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pulseDescriptorIndex', full_name='PulseP.pulseDescriptorIndex', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edgeOfScanLine', full_name='PulseP.edgeOfScanLine', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scanDirection', full_name='PulseP.scanDirection', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mirroFacet', full_name='PulseP.mirroFacet', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intensity', full_name='PulseP.intensity', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='classification', full_name='PulseP.classification', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=546,
)


_CHANNELP = _descriptor.Descriptor(
  name='ChannelP',
  full_name='ChannelP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='ChannelP.channel', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampleUnit', full_name='ChannelP.sampleUnit', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waveSegment', full_name='ChannelP.waveSegment', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=548,
  serialized_end=631,
)


_WAVESEGMENTP = _descriptor.Descriptor(
  name='WaveSegmentP',
  full_name='WaveSegmentP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='durationFromAnchor', full_name='WaveSegmentP.durationFromAnchor', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='echo', full_name='WaveSegmentP.echo', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=689,
)

_PWLISTP.fields_by_name['pulse'].message_type = _PULSEP
_PULSEP.fields_by_name['channels'].message_type = _CHANNELP
_CHANNELP.fields_by_name['waveSegment'].message_type = _WAVESEGMENTP
DESCRIPTOR.message_types_by_name['PWListP'] = _PWLISTP
DESCRIPTOR.message_types_by_name['PulseP'] = _PULSEP
DESCRIPTOR.message_types_by_name['ChannelP'] = _CHANNELP
DESCRIPTOR.message_types_by_name['WaveSegmentP'] = _WAVESEGMENTP

PWListP = _reflection.GeneratedProtocolMessageType('PWListP', (_message.Message,), dict(
  DESCRIPTOR = _PWLISTP,
  __module__ = 'pulsewaves_pb2'
  # @@protoc_insertion_point(class_scope:PWListP)
  ))
_sym_db.RegisterMessage(PWListP)

PulseP = _reflection.GeneratedProtocolMessageType('PulseP', (_message.Message,), dict(
  DESCRIPTOR = _PULSEP,
  __module__ = 'pulsewaves_pb2'
  # @@protoc_insertion_point(class_scope:PulseP)
  ))
_sym_db.RegisterMessage(PulseP)

ChannelP = _reflection.GeneratedProtocolMessageType('ChannelP', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELP,
  __module__ = 'pulsewaves_pb2'
  # @@protoc_insertion_point(class_scope:ChannelP)
  ))
_sym_db.RegisterMessage(ChannelP)

WaveSegmentP = _reflection.GeneratedProtocolMessageType('WaveSegmentP', (_message.Message,), dict(
  DESCRIPTOR = _WAVESEGMENTP,
  __module__ = 'pulsewaves_pb2'
  # @@protoc_insertion_point(class_scope:WaveSegmentP)
  ))
_sym_db.RegisterMessage(WaveSegmentP)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"umg.core.lidar.protobuf.pulsewavesB\010PWProtos'))
# @@protoc_insertion_point(module_scope)
